//This is the json file thats deleted by brad when it became useless, but when following the project, we need this file in order to see products on the webapp before moving on to "backend" module
//I think it might help save time for many learners

const products = [
  {
    _id: 1,
    name: "Computer Mouse",
    image: "https://source.unsplash.com/random?computer+mouse/200×300",
    description: "Removal of Intraluminal Device from Trachea, Endo",
    brand: "Oozz",
    category: "Western",
    price: 49.55,
    countInStock: 80,
    rating: 5,
    numReviews: 19,
  },
  {
    _id: 2,
    name: "Keyboard",
    image: "https://source.unsplash.com/random?keyboard/200×300",
    description: "Plain Radiography of All Teeth",
    brand: "Kanoodle",
    category: "Drama",
    price: 75.76,
    countInStock: 92,
    rating: 2,
    numReviews: 87,
  },
  {
    _id: 3,
    name: "Joystick",
    image: "https://source.unsplash.com/random?Joystick/200×300",
    description: "Drain of Thor Spinal Cord with Drain Dev, Perc Endo Approach",
    brand: "Twitterwire",
    category: "Crime|Drama",
    price: 85.96,
    countInStock: 13,
    rating: 3,
    numReviews: 41,
  },
  {
    _id: 4,
    name: "Computer Monitor",
    image: "https://source.unsplash.com/random?computer+monitor/200×300",
    description: "Revision of Extraluminal Device in Heart, Perc Endo Approach",
    brand: "Yakitri",
    category: "Drama",
    price: 64.48,
    countInStock: 59,
    rating: 2.5,
    numReviews: 63,
  },
  {
    _id: 5,
    name: "WebCam",
    image: "https://source.unsplash.com/random?Webcam/200×300",
    description: "Reposition Right Pelvic Bone, Percutaneous Approach",
    brand: "Photobug",
    category: "Horror",
    price: 2.99,
    countInStock: 52,
    rating: 1.5,
    numReviews: 19,
  },
  {
    _id: 6,
    name: "Bluetooth Speaker",
    image: "https://source.unsplash.com/random?Bluetooth+speaker/200×300",
    description: "Remove Synth Sub from Vagina & Cul-de-sac, Perc Endo",
    brand: "Devpulse",
    category: "Drama",
    price: 26.06,
    countInStock: 59,
    rating: 5,
    numReviews: 18,
  },
  {
    _id: 7,
    name: "USB LED",
    image: "https://source.unsplash.com/random?USB+light/200×300",
    description: "Drainage of Jejunum, Via Opening, Diagn",
    brand: "Yoveo",
    category: "Drama|Horror",
    price: 77.45,
    countInStock: 52,
    rating: 4,
    numReviews: 85,
  },
  {
    _id: 8,
    name: "SSD",
    image: "https://source.unsplash.com/random?SSD/200×300",
    description: "Revision of Nonaut Sub in L Tympanic Membrane, Open Approach",
    brand: "Livefish",
    category: "Animation|Children|Comedy|Romance",
    price: 68.66,
    countInStock: 28,
    rating: 2.5,
    numReviews: 89,
  },
  {
    _id: 9,
    name: "Portable Harddrive",
    image: "https://source.unsplash.com/random?portable+harddrive/200×300",
    description: "Insert of Infusion Dev into L Com Iliac Art, Open Approach",
    brand: "Realcube",
    category: "Children|Fantasy",
    price: 54.82,
    countInStock: 47,
    rating: 3.5,
    numReviews: 40,
  },
  {
    _id: 10,
    name: "Laptop Batteries",
    image: "https://source.unsplash.com/random?Laptop+Batteries/200×300",
    description: "Bypass Pancreatic Duct to Small Intestine, Open Approach",
    brand: "Quimm",
    category: "Animation|Comedy|Sci-Fi",
    price: 94.79,
    countInStock: 2,
    rating: 1,
    numReviews: 9,
  },
];

export default products;
